#!/usr/bin/env python3
import gi, signal
gi.require_version('Gtk', '3.0')
gi.require_version('AppIndicator3', '0.1')
from gi.repository import Gtk, AppIndicator3, GLib

indicator = AppIndicator3.Indicator.new(
    "whisper-ptt",
    "audio-input-microphone",
    AppIndicator3.IndicatorCategory.APPLICATION_STATUS
)
indicator.set_status(AppIndicator3.IndicatorStatus.ACTIVE)

menu = Gtk.Menu()
item = Gtk.MenuItem(label="Listening...")
item.set_sensitive(False)
menu.append(item)
menu.show_all()
indicator.set_menu(menu)

GLib.unix_signal_add(GLib.PRIORITY_DEFAULT, signal.SIGTERM, Gtk.main_quit)
signal.signal(signal.SIGINT, signal.SIG_DFL)

Gtk.main()
